name: empiricus_subscriptions
description: "Teste dev Empiricus."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.3.0
  json_annotation: ^4.9.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  assets:
    - assets/images/
  uses-material-design: true